default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: report_development


test:
  <<: *default
database: report_test